services:
  postgres:
    image: postgres:16
    container_name: magno-postgres
    environment:
      POSTGRES_DB: magno_db
      POSTGRES_USER: magno
      POSTGRES_PASSWORD: magno123
    ports:
      - "5432:5432"
    volumes:
      - magno_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: magno-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: magno-minio
    environment:
      MINIO_ROOT_USER: magno
      MINIO_ROOT_PASSWORD: magno123456
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - magno_minio_data:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc:latest
    container_name: magno-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 magno magno123456;
      mc mb --ignore-existing local/magno-files;
      mc anonymous set download local/magno-files;
      exit 0;
      "

volumes:
  magno_pgdata:
  magno_minio_data:
